export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const SET_LOADING = 'SET_LOADING'
export const SET_POSITION = 'SET_POSITION'
export const SET_USER = 'SET_USER'

export const ADD_SPORTTYPE = 'ADD_SPORTTYPE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const CHANGE_DATE = 'CHANGE_DATE'

export const SET_RESOURCE = 'SET_RESOURCE'