export const SET_LOADING = 'SET_LOADING'
export const SET_POSITION = 'SET_POSITION'
export const SET_USER = 'SET_USER'

export const ADD_SPORTTYPE = 'ADD_SPORTTYPE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const CHANGE_DATE = 'CHANGE_DATE'

export const SET_RESOURCE = 'SET_RESOURCE'
export const CLEAR_RESOURCE = 'CLEAR_RESOURCE'
export const SET_RESOURCE_STATE = 'SET_RESOURCE_STATE'
export const CACULATE_PAY ='CACULATE_PAY'